name: "my joke action"

description: "use an external API to retrieve and deisplay a joke"

outputs:
  joke-output:
    description: The resulting joke from the icanhazdadjokes API

runs: 
  using: "node16"
  main: "main.js"